#!/bin/sh

tar zcvf nvidia-widgets-`cat VERSION`.tar.gz \
	--exclude '.*' --exclude debian --exclude '*~' --exclude buildpkg \
	--exclude build --exclude data --exclude tags --exclude Makefile \
	--exclude 'nvidia-widgets-*.tar.gz' --exclude vc8 \
	--transform 's,^,nvidia-widgets/,' *
